export const ORDER_STATUS = {
  CREATED: 'CREATED',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  COLLECTED: 'COLLECTED',
  CANCELLED: 'CANCELLED',
} as const;

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.CREATED]: 'Created',
  [ORDER_STATUS.PROCESSING]: 'Processing',
  [ORDER_STATUS.READY]: 'Ready',
  [ORDER_STATUS.COLLECTED]: 'Collected',
  [ORDER_STATUS.CANCELLED]: 'Cancelled',
} as const;

export const ORDER_STATUS_LIST = [
  {
    id: ORDER_STATUS.CREATED,
    label: ORDER_STATUS_LABELS[ORDER_STATUS.CREATED],
  },
  {
    id: ORDER_STATUS.PROCESSING,
    label: ORDER_STATUS_LABELS[ORDER_STATUS.PROCESSING],
  },
  {
    id: ORDER_STATUS.READY,
    label: ORDER_STATUS_LABELS[ORDER_STATUS.READY],
  },
  {
    id: ORDER_STATUS.COLLECTED,
    label: ORDER_STATUS_LABELS[ORDER_STATUS.COLLECTED],
  },
  {
    id: ORDER_STATUS.CANCELLED,
    label: ORDER_STATUS_LABELS[ORDER_STATUS.CANCELLED],
  },
];
