export const ACTION_TYPES = {
  CHANGE_STORE: 'CHANGE_STORE',
  CHANGE_START_TIME: 'CHANGE_START_TIME',
  CHANGE_END_TIME: 'CHANGE_END_TIME',
  CHANGE_STATUS: 'CHANGE_STATUS',
  SUBMIT: 'SUBMIT',
  RESET: 'RESET',
} as const;
